# For more information: https://laravel.com/docs/sail
version: '3'
services:
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'mysql-data:/var/lib/mysql'
            - './docker/db/my.cnf:/etc/mysql/conf.d/my.cnf'
            - './docker/db/sql:/docker-entrypoint-initdb.d'
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
    api:
        build: .
        ports:
            - '${FORWARD_APP_PORT:-8080}:8000'
        volumes:
            - node_modules:/app/node_modules
            - .:/app
        command: php artisan octane:start --watch --host=0.0.0.0 --port=8000
    # queue:
    #     build:
    #         dockerfile: Dockerfile-rabbitmq
    #         context: .
    #     ports:
    #         - '5672:5672'
    #         - '15672:15672'

volumes:
    mysql-data:
    node_modules:
