name: Deploy

on:
  workflow_run:
    workflows: [Test]
    types: [completed]
    branches: [main]

permissions:
  contents: read

jobs:
  Deploy:
    runs-on: self-hosted
    environment: production
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Wait for tests to succeed
      uses: lewagon/wait-on-check-action@v1.3.1
      with:
        ref: ${{ github.ref }}
        check-name: 'Run tests'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        wait-interval: 10

    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: bdd-analyser-api-app

    - name: Move artifact to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "release.zip"
        target: "/var/tmp/"

    - name: Deploy app to server
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        port: ${{ secrets.PORT }}
        script: |
          ls
          unzip /var/tmp/release.zip /var/sites/bdd-analysis-api/release/
          chmod a+x /var/sites/bdd-analysis-api/release/deploy/deploy.sh
          /var/sites/bdd-analysis-api/release/deploy/deploy.sh "/var/sites/bdd-analysis-api/"
  OnFailure:
    runs-on: ubuntu-latest
      if: ${{ github.event.workflow_run.conclusion == 'failure' }}
      steps:
        - run: echo 'The triggering workflow failed'

  health-check:
    runs-on: self-hosted
    needs: deploy
    steps:
    - name: Check if app still responds as it should.
      run: curl https://bdd-analyser-api.inevitabletech.uk/
