name: Test
on: [push]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: composer

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Setup app
      env:
        DB_CONNECTION=mysql
        DB_HOST=mysql
        DB_PORT=3306
        DB_DATABASE=bdd_analyser_console
        DB_USERNAME=api
        DB_PASSWORD=secret
        AUTH_TOKEN=averysecrettokenforapiauthorization==
      run: |
        make artisan key:generate
        make run
        make rebuild-db

    - name: Run test suite
      run: make tests
