name: Test

on: [push]

# permissions:
#   contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        tools: composer

    - name: Prepull docker images
      run: |
        docker-compose pull mysql &

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Setup app
      run: |
        cp .env.example .env

        echo DB_CONNECTION=mysql >> .env
        echo DB_HOST=mysql >> .env
        echo DB_PORT=3306 >> .env
        echo DB_DATABASE=bdd_analyser_console >> .env
        echo DB_USERNAME=api >> .env
        echo DB_PASSWORD=secret >> .env
        echo AUTH_TOKEN=averysecrettokenforapiauthorization== >> .env

        make artisan a=key:generate
        make install-dirs
        make run
        docker ps
        docker-compose logs api
        docker-compose logs mysql

        sleep 20

        make rebuild-db

    - name: Run test suite
      run: make tests

    - name: create zip and archive
      run: |
        zip release.zip ./* -r

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: bdd-analyser-api-app
        path: release.zip

  deploy:
    runs-on: ubuntu-latest
    environment: production
    needs: [test]
    # if: github.ref == 'refs/heads/main'
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: bdd-analyser-api-app

    - name: Display structure of downloaded files
      run: ls -R

    - name: Move artifact to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "release.zip"
        target: "/var/tmp/"

    - name: Deploy app to server
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        port: ${{ secrets.PORT }}
        script: |
          ls
          unzip /var/tmp/release.zip /var/sites/bdd-analysis-api/release/
          chmod a+x /var/sites/bdd-analysis-api/release/deploy/deploy.sh
          /var/sites/bdd-analysis-api/release/deploy/deploy.sh "/var/sites/bdd-analysis-api/"
  # on-failure:
  #   runs-on: ubuntu-latest
  #   if: ${{ github.event.workflow_run.conclusion == 'failure' }}
  #   steps:
  #     - run: echo 'The triggering workflow failed'